### ISSUE TITLE
Higher resolution for the icons?

### ISSUE THREAD

**Issue by R8s6** [zwpwjwtz/f3-qt#10]
The Settings, Help and Back buttons have very low resolutions and result in blurry icons on 2k or 4k monitors.

Examples: 
https://i.imgur.com/Uq3ev9D.png
https://i.imgur.com/EbKXIjg.png

Not an urgent issue, but it's good to have hi-res icons.

Thank you very much.

**Comment by zwpwjwtz** [comment]
Fixed in e9c251b

**Comment by R8s6** [comment]
Hi,

Thanks for the update, it's a lot better for sure!

However, the images still appear to be not sharp enough. 

But it appears to be **aliasing** caused by "resizing" or "scaling" of the png files.

I can see that the "back.png" and "help.png" are pretty good at its original size (seen in a browser):
![](https://i.imgur.com/ZmTRzjy.png)
![](https://i.imgur.com/Ocx9Hhc.png)

But perhaps when these png images are resized to a smaller size in the UI, they now have [aliasing](https://en.wikipedia.org/wiki/Aliasing) on the "back", "help" and "advanced" buttons:
![](https://i.imgur.com/r66grZ6.png)
![](https://i.imgur.com/gx84zbZ.png)

I don't have any experience in developing UI, so I might be asking too much, but it'll be great if the png files could be replaced by vector images such as [svg](https://en.wikipedia.org/wiki/Scalable_Vector_Graphics) image files?

This is only cosmetic and not urgent, so please don't feel pressured. 

I'm already very thankful for all you have done, this is a great tool. Thank you very much!

**Comment by zwpwjwtz** [comment]
Yes, this is due to resizing issues when Qt try to scale bitmaps.
Currently, using SVG would be a better resolution, but it requires extra module (QtSvg) to be linked during build. I'll try to reconsider the UI design later.
